### ISSUE TITLE
If you can / Think it is needed

### ISSUE THREAD

**Issue by JudeGrodesky** [Mackswehl/Hawdogs#2]
Find a way to type up the flow chart currently in the repository without losing clarity. If no one does, I have the hand written hard copy to give in tomorrow (1/10)

**Comment by MaxwellVale** [comment]
Ok yeah I'll try and find a website to remake the flowchart. I think I've used one before.

**Comment by MaxwellVale** [comment]
Ok I made a Flowchart. It looks pretty similar so just check it out.
